[package]
name = "PolisAndSiege"
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { version = "0.81.0", features = ["gl", "textlayout", "svg"] }
rand = "0.9.1"
petgraph = "0.8.1"
ciborium = "0.2.2"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"] }
gl = "0.14.0"
